
export interface FanartItem {
  id: number
  src: string
  alt: string
  artist: string
  artistHandle: string
  artistUrl: string
  artistPfp: string
  likes?: 0 | number
  tags?: string[]
  size: 'normal' | 'tall' | 'wide'
}

export const fanartsRaw: FanartItem[] = [
  {
    id: 1,
    src: '/images/trucking.jpg',
    alt: 'Trucking through the night',
    artist: 'Nyxx and Luminae',
    artistHandle: '@nyxxluminae',
    artistUrl: 'https://instagram.com/nyxxluminae',
    artistPfp: '/pfp/nyxxluminae.jpg',
    size: 'tall',
  },
  {
    id: 2,
    src: '/images/doodlepaper.jpg',
    alt: 'Akoji doodle on a paper',
    artist: 'Sunink_',
    artistHandle: '@sunink_',
    artistUrl: 'https://twitter.com',
    artistPfp: '/pfp/sunink_.webp',
    size: 'normal',
  },
  {
    id: 3,
    src: '/images/mleague.png',
    alt: 'MLeague watch party with friends',
    artist: 'Mikidayoooo',
    artistHandle: '@miki_dayoooo',
    artistUrl: 'https://twitter.com/miki_dayoooo',
    artistPfp: '/pfp/mikidayoooo.webp',
    size: 'wide',
  },
  {
    id: 4,
    src: '/images/losingstreak.jpg',
    alt: 'Akoji after 10 games of Mahjong without a win',
    artist: 'Victtr',
    artistHandle: '@victtr',
    artistUrl: 'https://twitter.com',
    artistPfp: '/pfp/default.png',
    size: 'tall',
  },
  {
    id: 5,
    src: '/images/doodle.png',
    alt: 'A doodle of Akoji by Rainemonn',
    artist: 'Rainemonn',
    artistHandle: '@rainemonn',
    artistUrl: 'https://twitter.com/rainemonn',
    artistPfp: '/pfp/rainemonn.webp',
    size: 'normal',
  },
  {
    id: 6,
    src: '/images/freebies.png',
    alt: 'Thankful freebie for the commission',
    artist: 'Kuroba Reena',
    artistHandle: '@KurobaReena',
    artistUrl: 'https://twitter.com/KurobaReena',
    artistPfp: '/pfp/kurobareena.jpg',
    size: 'normal',
  },
  {
    id: 7,
    src: '/images/tiramisu.jpg',
    alt: 'Akoji and his favorite dessert, tiramisu. Happy birthday, Akoji!',
    artist: 'Meiwhalien',
    artistHandle: '@Meiwhalien',
    artistUrl: 'https://twitter.com/Meiwhalien',
    artistPfp: '/pfp/meiwhalien.jpg',
    tags: ['Birthday'],
    size: 'normal',
  },
  {
    id: 8,
    src: '/images/qipao.png',
    alt: 'Lore accurate of Akoji in a qipao (slander)',
    artist: 'Erion Vayle',
    artistHandle: '@ErionVayle',
    artistUrl: 'https://twitter.com/ErionVayle',
    artistPfp: '/pfp/erionvayle.jpg',
    tags: ['Birthday'],
    size: 'tall',
  },
  {
    id: 9,
    src: '/images/smug.png',
    alt: 'Akoji looking smug (Happy Birthday, Akoji!)',
    artist: 'Miixumi',
    artistHandle: '@miixumi',
    artistUrl: 'https://twitter.com/miixumi',
    artistPfp: '/pfp/miixumi.jpg',
    tags: ['Birthday'],
    size: 'normal',
  },
  {
    id: 10,
    src: '/images/akochad.png',
    alt: 'Akoji is a gigachad (Happy Birthday, Akoji!)',
    artist: 'Miixumi',
    artistHandle: '@miixumi',
    artistUrl: 'https://twitter.com/miixumi',
    artistPfp: '/pfp/miixumi.jpg',
    tags: ['Birthday'],
    size: 'normal',
  },
  {
    id: 11,
    src: '/images/akonyan.jpg',
    alt: 'Akonyaaan~ (Happy Birthday, Akoji!)',
    artist: 'Yuikizu',
    artistHandle: '@yuikizu',
    artistUrl: 'https://twitter.com/yuikizu',
    artistPfp: '/pfp/yuikizu.jpg',
    tags: ['Birthday'],
    size: 'normal',
  },
  {
    id: 12,
    src: '/images/mahjong.png',
    alt: 'Keep up the mahjong spirit (Happy Birthday, Akoji!)',
    artist: 'Mikidayoooo',
    artistHandle: '@miki_dayoooo',
    artistUrl: 'https://twitter.com/miki_dayoooo',
    artistPfp: '/pfp/mikidayoooo.webp',
    tags: ['Birthday'],
    size: 'wide',
  },
  {
    id: 13,
    src: '/images/hbd.png',
    alt: 'Happy 136th Birthday, Akoji!',
    artist: 'Ryuna Zahra',
    artistHandle: '@ryunazahra',
    artistUrl: 'https://twitter.com/ryunazahra',
    artistPfp: '/pfp/ryunazahra.jpg',
    tags: ['Birthday'],
    size: 'normal',
  },
  {
    id: 14,
    src: '/images/couple.png',
    alt: 'Akoji and Meiwhalien',
    artist: 'Rainemonn',
    artistHandle: '@rainemonn',
    artistUrl: 'https://twitter.com/rainemonn',
    artistPfp: '/pfp/rainemonn.webp',
    size: 'wide',
  },
  {
    id: 15,
    src: '/images/affiliate.png',
    alt: 'Happy First Affiliate, Akoji!',
    artist: 'Kuroba Reena',
    artistHandle: '@KurobaReena',
    artistUrl: 'https://twitter.com/KurobaReena',
    artistPfp: '/pfp/kurobareena.jpg',
    size: 'normal',
  },
  {
    id: 15,
    src: '/images/chibihead.png',
    alt: 'Art trade for Ryuna Birthday',
    artist: 'Ryuna Zahra',
    artistHandle: '@ryunazahra',
    artistUrl: 'https://twitter.com/ryunazahra',
    artistPfp: '/pfp/ryunazahra.jpg',
    size: 'normal',
  },
]